---
name: featmap-build
run-name: Build Featmap from source
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Install go-bindata
        run: go install github.com/go-bindata/go-bindata/go-bindata@latest
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV
      - name: Build from source
        run: make
      - name: Build and push Core container image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: quay.io/labmonkeys/featmap:latest
